# Default values for arm64v8-yacy
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

terminationGracePeriodSeconds: 300

image:
  repository: jkaldon/arm64v8-yacy
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "Release_1.92-4"
  lifecycle:
    preStop:
      exec:
        command: ["/home/yacy/dist/stopYACY.sh"]
  resources:
    requests:
      cpu: 1000m
      memory: 5Gi
    limits:
      cpu: 4000m
      memory: 6Gi

#initEnv:
#- name: RPC_USERNAME
#  value: admin
#- name: RPC_PASSWORD
#  value: your_secret_password

persistence:
  enabled: true
  ## A manually managed Persistent Volume and Claim
  ## Requires persistence.enabled: true
  ## If defined, PVC must be created manually before volume will be bound
  existingClaim:
  ## jenkins data Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  storageClass: nfs-client
  annotations: {}
  accessMode: "ReadWriteOnce"
  size: "8Gi"
  volumes:
  - name: yacy-data
    persistentVolumeClaim:
      claimName: yacy
  mounts:
  - name: yacy-data
    mountPath: /data
    readOnly: false

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext:
  fsGroup: 1000

securityContext:
  capabilities:
    drop:
    - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  ports:
    - port: 8090
      targetPort: 8090
      protocol: TCP
      name: http

ingress:
  enabled: true
  paths: []
  labels: {}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
  hostName: yacy.kaldon.com
  tls:
  - secretName: tls-yacy.kaldon.com
    hosts:
    - yacy.kaldon.com
